### ISSUE TITLE
功能建议！！！

### ISSUE THREAD

**Issue by eval3** [lzjin/ViewPagerGallery#5]
首先感谢大佬给予的Demo，我建议还可以加上“控制轮播速度”、“滑动时取消延时，当手指离开屏幕后才会重新开始计时”，我觉得这两个功能在大多数带有轮播图的App上都有这样的功能，我希望Banner也能做到这样！！！（我都修改好了，我可以发到自己的Github上吗？）

**Comment by ll418718** [comment]
> 首先感谢大佬给予的Demo，我建议还可以加上“控制轮播速度”、“滑动时取消延时，当手指离开屏幕后才会重新开始计时”，我觉得这两个功能在大多数带有轮播图的App上都有这样的功能，我希望Banner也能做到这样！！！（我都修改好了，我可以发到自己的Github上吗？）

请问能把demo共享学习一下吗？感谢大佬

**Comment by eval3** [comment]
这是我的一个小项目，我现在放在了码云上https://gitee.com/MakerJoson/familyEducationHelp.git

**Comment by lzjin** [comment]
滑动时取消延时已加
